# 통합 테스트 등 DB가 필요한 테스트용 : 초기화된 DB, 빠른 실행, 불필요한 로그 생략
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 후 자동 삭제
    show-sql: false # SQL 쿼리 로그 비활성화