# 개발팀용 WAS 서버용 설정
# S3 파일 저장, 실제 개발 서버
# 디버깅이 목적 (SQL로그와 바인딩 값 확인)

spring:
  datasource:
    # 지금은 local과 같은 서버 사용중
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_yeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

logging:
  level:
    root: info # 개발 단계에서는 debug 레벨로 설정
    com.example: debug # 내 서비스 패키지만 디버깅 ((TRACE < DEBUG < INFO < WARN < ERROR))
    org.hibernate.SQL: debug # SQL 쿼리 로그 레벨
    org.hibernate.type.descriptor.sql.BasicBinder: trace # SQL 바인딩 로그 레벨

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 콘솔 로그 포맷