# 운영용 서버
# 로그 압축, 파일 저장 경로, 보안 DB
# 콘솔 출력 최소화 + 로그 파일 저장 + 용량 제한이 목적

spring:
  datasource:
    # 지금은 local과 같은 서버 사용중
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_yeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

logging:
  level:
    root: info # 운영에서는 info/warn 레벨로 설정

  file:
    name: logs/app-prod.log  # 로그 파일 저장 경로

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 파일 로그 포맷

  logback:
    rollingpolicy:
      max-file-size: 10MB # 최대 파일 크기
      max-history: 7 # 최대 보관 일수